### ISSUE TITLE
bulid error on MacOS Catalina

### ISSUE THREAD

**Issue by brianmcfadden** [PirateNetwork/pirate#68]
**Describe the bug**
Since commit 68e4a6691249b7a41482ed55b37301edc210f8ea (Merge remote-tracking branch 'komodo/dev' into pirate_da_dev), I've been unable to compile for Mac OS.  I'm receiving a group of errors for PACKAGE_* and VERSION macros.   A sample of the #define issue is here:
`
In file included from cc/../secp256k1/src/field.h:22,
                 from cc/../secp256k1/src/group.h:11,
                 from cc/../secp256k1/src/ecmult.h:46,
                 from cc/musig.cpp:186,
                 from cc/cclib.cpp:701:
cc/../secp256k1/src/libsecp256k1-config.h:72: error: "PACKAGE_BUGREPORT" redefined [-Werror]
 #define PACKAGE_BUGREPORT ""
 
In file included from ./compat/endian.h:9,
                 from ./serialize.h:24,
                 from ./amount.h:24,
                 from ./primitives/transaction.h:24,
                 from ./primitives/block.h:24,
                 from cc/cclib.cpp:19:
./config/bitcoin-config.h:302: note: this is the location of the previous definition
 #define PACKAGE_BUGREPORT "https://github.com/PirateNetwork/Pirate/issues" 
 `
There are also 2 more errors in dilithium_spend() and dilithium_Qsend(), lines 3322 and 3418, respectively, in dilithium.c.  The error produced is "error: ISO C++ forbids converting a string constant to 'char*'", and it seems to relate to the definition of *retstr="" in near the top of both of those functions.

**To Reproduce**

1. Build for mac with ./zcutil/build-mac.sh

**Expected behavior**
The build would complete successfully.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version 10.15.7 Catalina

**Additional context**
A build log is attached.
[build.log](https://github.com/PirateNetwork/pirate/files/6698407/build.log)

**Comment by CryptoForge** [comment]
@brianmcfadden I think this is fixed in the beta branch if you want to give it a try.

**Comment by brianmcfadden** [comment]
@CryptoForge The build on the beta branch worked fine.  There's still an issue with the fetch (sprout-proving.key.dl: FAILED, 1 computed checksum did NOT match), but the build errors on MacOS are fixed. so the issue can be closed.
